export const columns = [
    <p className="text-center">Project Manager</p>,
    <p className="text-center">No. of Projects <br /> <span className="highlight">{'(Minimum Ideal 18)'}</span> </p>,
    <p className="text-center">Total Project Value <br /> <span className="highlight">{'(Minimum Ideal 8000 USD)'}</span> </p>,
    <p className="text-center">Total Released Amount</p>,
    <p className="text-center">No. of <br /> Fully Completed Project</p>,
    <p className="text-center">No. of Completed Projects <br />Without Authorization</p>,
    <p className="text-center">Project Completion Rate <br /> <span className="highlight">{'(Minimum Ideal 85%)'}</span> </p>,
    <p className="text-center">Project Completion Rate <br /> <span>{'(Without Authorization)'}</span> </p>,
    <p className="text-center">No. of First Time Clients</p>,
    <p className="text-center">Milestone Completion Rate</p>,
    <p className="text-center">Task Completion Rate</p>,
    <p className="text-center">Average Project Completion Time</p>,
    <p className="text-center">No. of Upsale/Cross Sales</p>,
    <p className="text-center">Value of Upsale/Cross Sales</p>,
    <p className="text-center">Canceled Projects</p>,
    <p className="text-center">Delayed Projects</p>,
    <p className="text-center">Delayed Completed</p>,
    <p className="text-center">Percentage of br Delayed Projects</p>,
    <p className="text-center">Cancelation Rate</p>,
    <p className="text-center">Avg. Payment Rel. Time</p>,
]